[package]
name = "matroska"
description = "Matroska/WebM demuxer"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
readme = "README.md"
license = "MIT"

[lib]
name = "matroska"
path = "src/lib.rs"

[[bin]]
name = "matroska_info"
path = "src/bin/matroska_info.rs"

[dependencies]
nom = { git = "https://github.com/Geal/nom", branch="result" }
cookie-factory = "^0.2"
av-data = { version = "0.1.0", path = "../rust-av/data" }
av-format = { version = "0.1.0", path = "../rust-av/format" }
circular = { git = "https://github.com/sozu-proxy/circular" }

[dev-dependencies]
quickcheck = "0.3"
